services:
  db:
    image: mysql:9.1.0
    container_name: orders_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: orders_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: Password123!
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data: